---
env:
    es6: true
    browser: true
    es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 12
    sourceType: module

rules:
    quotes:
        - error
        - single
    prettier/prettier: 2

plugins:
    - prettier
    - '@typescript-eslint'

extends:
    - plugin:prettier/recommended
    - prettier
    - google
