name: CI

on:
  push:
    branches: [ develop ]

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Test Application
        run: npm run test

      # - name: Deploy Next js Application to Vercel
      #   uses: amondnet/vercel-action@v20
      #   id: vercel
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required 
      #     scope: ${{ secrets.VERCEL_TEAM_ID }}
          
      # - name: Run Lighthouse
      #   uses: foo-software/lighthouse-check-action@master
      #   with:
      #     accessToken: ${{ secrets.GITHUB_TOKEN }}
      #     prCommentEnabled: true
      #     urls: ${{ steps.vercel.outputs.preview-url }}